### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by mcpeblocker** [Olmos-jamoasi/Kalit#1]
1. Mobile uchun Flutter ishlatilayotgan boʻlsa desktopniyam Flutterda qigan yaxshimasmi?
Kerakli joylarda Electronda OS yoki native environment bilan ishlash qiyinchilik tugʻdirishi mumkin deb oʻylayman va performance tomonidan ham Flutter yaxshiroq boʻlsa kerak.

2. Logikada hamma encryptionlar client tomonda qilinadi deyilgan ekan. Bunda security risklar oshmaydimi? Maʼlumot clientda encrypt qilinsa va toʻgʻridan toʻgʻri serverga yuborib saqlab qoʻyilsa (validatsiya qimasdan serverda) hujum uyushtirilganda himoyasi zaif boʻladi fikrimcha. Keyinchalik tizimning clientʼi sifatida 'pretend' qilishga muvaffaq boʻlgan odam serverda xohlagan narsasini saqlayveradigan boʻb qolmaydimi?

**Comment by Jakhongiirr** [comment]
Desktopni tauriga òzgartiramiz, flutterni ham kòrib chiqamiz, security bòyicha research qilyapmiz 3-4ta variantlani))
